server:
  port: 8090

#session 유지시간 변경(기본은 30분)
  servlet:
    session:
      timeout: 90m
#mysql setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-324ob8-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123

#jpa setting
#스키마 생성 create: 애플리케이션 시작 시 테이블 새로 생성 / update: 엔티티에 맞게 자동으로 테이블 수정 / none: 아무것도 안 함
  jpa:
    hibernate:
      ddl-auto: update
#ddl 생성시 데이터베이스 고유의 기능을 사용할 것인가
    generate-ddl: true
#api 호출 시 실행된느 sql 문을 콘솔에 보여줄 것인가
    show-sql: false
#사용할 데이터베이스 종류
    database: mysql
#Mysql 상세 지정
    database-platform: org.hibernate.dialect.MySQLDialect